COMPILE_DEPS = [
  '//lib:CORE_DEPS',
  '//core/store/serializers:onos-core-serializers',
  '//lib:org.apache.karaf.shell.console',
  '//core/api:onos-api',
  '//lib:javax.ws.rs-api',
  '//lib:jersey-server',
  '//utils/rest:onlab-rest',
  '//incubator/net:onos-incubator-net',
]


osgi_jar_with_tests (
  deps = COMPILE_DEPS,
  web_context = '/onos/novibng',
  api_title = 'ONOS NoviBng REST API',
  api_version = '1.0',
  api_description = 'APIs for interacting with the Noviflow BNG application.',
  api_package = 'org.onosproject.novibng.web',
)

onos_app (
  title = 'NoviFlow vBNG',
  category = 'Traffic Steering',
  url = 'http://onosproject.org',
  description = 'app to implement a vBNG on a NoviFlow.',
)
