COMPILE_DEPS = [
  '//lib:CORE_DEPS',
  '//core/store/serializers:onos-core-serializers',
  '//lib:org.apache.karaf.shell.console',
  '//core/api:onos-api',
  '//lib:javax.ws.rs-api',
  '//lib:jersey-server',
  '//utils/rest:onlab-rest',
]


osgi_jar_with_tests (
  deps = COMPILE_DEPS,
)

onos_app (
  title = 'NoviFlow vBNG',
  category = 'Traffic Steering',
  url = 'http://onosproject.org',
  description = 'app to implement a vBNG on a NoviFlow.',
)
